CREATE OR REPLACE VIEW SQA_DRE_GERENCIAL AS
SELECT
    CAB.DTNEG AS DTREF
     , TO_CHAR(CAB.DTNEG,'MM') AS MES
     , TO_CHAR(CAB.DTNEG,'YYYY') AS ANO
     , ITE.NUNOTA
     , CAB.NUMNOTA
     , CAB.CODEMP
     , EMP.CODEMPMATRIZ
     , CAB.CODPARC
     , ITE.CODPROD
     , PRO.DESCRPROD
     , PRO.CODGRUPOPROD
     , GRU.DESCRGRUPOPROD
     , GRUPAI.CODGRUPOPROD AS CODGRUPOPROD_PAI
     , GRUPAI.DESCRGRUPOPROD AS DESCRGRUPOPROD_PAI
     , GRUAVO.CODGRUPOPROD AS CODGRUPOPROD_AVO
     , GRUAVO.DESCRGRUPOPROD AS DESCRGRUPOPROD_AVO
     , CAB.CODTIPOPER
     , CAB.CODCENCUS
     , CUS.DESCRCENCUS
     , CUSPAI.CODCENCUS AS CODCENCUS_PAI
     , CUSPAI.DESCRCENCUS AS DESCRCENCUS_PAI
     , CUSAVO.CODCENCUS AS CODCENCUS_AVO
     , CUSAVO.DESCRCENCUS AS DESCRCENCUS_AVO
     , CAB.CODNAT
     , NAT.DESCRNAT
     , NATPAI.CODCENCUS AS CODNAT_PAI
     , NATPAI.DESCRNAT AS DESCRNAT_PAI
     , NATAVO.CODNAT AS CODNAT_AVO
     , NATAVO.DESCRNAT AS DESCRNAT_AVO
     , CASE
           WHEN CAB.TIPMOV = 'V' THEN (ITE.VLRTOT)
           WHEN CAB.TIPMOV = 'D' THEN (ITE.VLRTOT) * -1
           WHEN CAB.TIPMOV = 'C' THEN (ITE.VLRTOT) * -1
           WHEN CAB.TIPMOV = 'E' THEN (ITE.VLRTOT)
    END AS VALOR
     , 'ESTOQUE' AS ORIGEM
     , CLAS.ORDEM AS AGRUPADOR
     , CLAS.CLASSIFICADOR AS NOME_AGRUPADOR

FROM TGFCAB CAB
         INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
         INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
         INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
         LEFT JOIN TGFGRU GRUPAI ON GRU.CODGRUPAI = GRUPAI.CODGRUPOPROD
         LEFT JOIN TGFGRU GRUAVO ON GRUPAI.CODGRUPAI = GRUAVO.CODGRUPOPROD
         INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
         LEFT JOIN TGFNAT NAT ON NAT.CODNAT = CAB.CODNAT
         LEFT JOIN TGFNAT NATPAI ON NAT.CODNATPAI = NATPAI.CODNAT
         LEFT JOIN TGFNAT NATAVO ON NATPAI.CODNATPAI = NATAVO.CODNAT
         LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = CAB.CODCENCUS
         LEFT JOIN TSICUS CUSPAI ON CUS.CODCENCUSPAI = CUSPAI.CODCENCUS
         LEFT JOIN TSICUS CUSAVO ON CUSPAI.CODCENCUSPAI = CUSAVO.CODCENCUS
         INNER JOIN AD_SQADRE CLAS ON CLAS.CODNAT = NAT.CODNAT

WHERE
    CAB.STATUSNOTA = 'L'
  AND CAB.TIPMOV IN ('V','D','C','E')

UNION ALL

SELECT
    CAB.DTNEG AS DTREF
     , TO_CHAR(CAB.DTNEG,'MM') AS MES
     , TO_CHAR(CAB.DTNEG,'YYYY') AS ANO
     , ITE.NUNOTA
     , CAB.NUMNOTA
     , CAB.CODEMP
     , EMP.CODEMPMATRIZ
     , CAB.CODPARC
     , ITE.CODPROD
     , PRO.DESCRPROD
     , PRO.CODGRUPOPROD
     , GRU.DESCRGRUPOPROD
     , GRUPAI.CODGRUPOPROD AS CODGRUPOPROD_PAI
     , GRUPAI.DESCRGRUPOPROD AS DESCRGRUPOPROD_PAI
     , GRUAVO.CODGRUPOPROD AS CODGRUPOPROD_AVO
     , GRUAVO.DESCRGRUPOPROD AS DESCRGRUPOPROD_AVO
     , CAB.CODTIPOPER
     , CAB.CODCENCUS
     , CUS.DESCRCENCUS
     , CUSPAI.CODCENCUS AS CODCENCUS_PAI
     , CUSPAI.DESCRCENCUS AS DESCRCENCUS_PAI
     , CUSAVO.CODCENCUS AS CODCENCUS_AVO
     , CUSAVO.DESCRCENCUS AS DESCRCENCUS_AVO
     , 30000000 AS CODNAT
     , 'CMV ' AS DESCRNAT
     , NATPAI.CODCENCUS AS CODNAT_PAI
     , NATPAI.DESCRNAT AS DESCRNAT_PAI
     , NATAVO.CODNAT AS CODNAT_AVO
     , NATAVO.DESCRNAT AS DESCRNAT_AVO
     , NVL((SELECT SUM(CUS.CUSSEMICM*ITE.QTDNEG)
            FROM TGFCUS CUS
            WHERE CUS.CODEMP = CAB.CODEMP
              AND CUS.CODPROD = ITE.CODPROD
              AND CUS.DTATUAL = (SELECT MAX(DTATUAL)
                                 FROM TGFCUS
                                 WHERE CODEMP = CUS.CODEMP
                                   AND CODPROD = CUS.CODPROD AND DTATUAL <= CAB.DTNEG)),0) * DECODE(CAB.TIPMOV, 'V', -1, 'D', 1) AS CUSTOTOTAL
     ,'CUSTO' AS ORIGEM
     , 3000 AS AGRUPADOR
     , CLAS.CLASSIFICADOR AS NOME_AGRUPADOR

FROM TGFCAB CAB
         INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
         INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
         INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
         LEFT JOIN TGFGRU GRUPAI ON GRU.CODGRUPAI = GRUPAI.CODGRUPOPROD
         LEFT JOIN TGFGRU GRUAVO ON GRUPAI.CODGRUPAI = GRUAVO.CODGRUPOPROD
         INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
         LEFT JOIN TGFNAT NAT ON NAT.CODNAT = CAB.CODNAT
         LEFT JOIN TGFNAT NATPAI ON NAT.CODNATPAI = NATPAI.CODNAT
         LEFT JOIN TGFNAT NATAVO ON NATPAI.CODNATPAI = NATAVO.CODNAT
         LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = CAB.CODCENCUS
         LEFT JOIN TSICUS CUSPAI ON CUS.CODCENCUSPAI = CUSPAI.CODCENCUS
         LEFT JOIN TSICUS CUSAVO ON CUSPAI.CODCENCUSPAI = CUSAVO.CODCENCUS
         INNER JOIN AD_SQADRE CLAS ON CLAS.CODNAT = NAT.CODNAT

WHERE CAB.STATUSNOTA = 'L'
  AND CAB.TIPMOV IN ('V','D')
  AND CAB.CODNAT IN (SELECT CODNAT FROM AD_SQADRE WHERE ORDEM = 1)

/*UNION ALL

SELECT
ITE.NUNOTA
, CAB.NUMNOTA
, ITE.CODPROD
, PRO.CODGRUPOPROD
, CAB.DTNEG AS DTREF
, TO_CHAR(CAB.DTNEG,'MM') AS MES
, TO_CHAR(CAB.DTNEG,'YYYY') AS ANO
, CAB.CODEMP
, EMP.CODEMPMATRIZ
, CAB.CODTIPOPER
, CAB.CODCENCUS
, CUS.DESCRCENCUS
, 40000000                   AS CODNAT
, 'IMPOSTOS SOBRE VENDAS'    AS DESCRNAT
, VALOR * -1                 AS VALOR
, 'IMPOSTOS'                 AS ORIGEM
, 2                          AS ORDEM
, (SELECT OPCAO FROM TDDOPC WHERE NUCAMPO = (SELECT NUCAMPO FROM TDDCAM WHERE NOMETAB = 'TGFDIN' AND NOMECAMPO = 'CODIMP') AND VALOR = DIN.CODIMP) AS NOME_CLASSIFICADOR

FROM TGFCAB CAB
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = CAB.CODCENCUS
INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFDIN DIN ON DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFTOP TTP ON TTP.CODTIPOPER = CAB.CODTIPOPER AND TTP.DHALTER = CAB.DHTIPOPER
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP

WHERE
TTP.GOLSINAL = -1
AND TTP.GOLDEV = 1
AND CAB.STATUSNOTA = 'L'
AND CAB.TIPMOV IN ('V','D','E','C')
AND DIN.CODIMP IN (1,4,6,7)*/

UNION ALL

SELECT
FIN.DTNEG AS DTREF
, TO_CHAR(FIN.DTNEG,'MM') AS MES
, TO_CHAR(FIN.DTNEG,'YYYY') AS ANO
, FIN.NUFIN
, FIN.NUMNOTA
, FIN.CODEMP
, EMP.CODEMPMATRIZ
, FIN.CODPARC
, 0 AS CODPROD
, '' AS DESCRPROD
, 0 AS CODGRUPOPROD_PAI
, '' AS DESCRGRUPOPROD_PAI
, 0 AS CODGRUPOPROD_AVO
, '' AS DESCRGRUPOPROD_AVO
, FIN.CODTIPOPER
, FIN.CODCENCUS
, CUS.DESCRCENCUS
, CUSPAI.CODCENCUS AS CODCENCUS_PAI
, CUSPAI.DESCRCENCUS AS DESCRCENCUS_PAI
, CUSAVO.CODCENCUS AS CODCENCUS_AVO
, CUSAVO.DESCRCENCUS AS DESCRCENCUS_AVO
, FIN.CODNAT
, NAT.DESCRNAT
, NATPAI.CODCENCUS AS CODNAT_PAI
, NATPAI.DESCRNAT AS DESCRNAT_PAI
, NATAVO.CODNAT AS CODNAT_AVO
, NATAVO.DESCRNAT AS DESCRNAT_AVO
, FIN.VLRDESDOB * FIN.RECDESP AS VALOR
, 'FINANCEIRO'                AS ORIGEM
, CLAS.ORDEM AS AGRUPADOR
, CLAS.CLASSIFICADOR          AS NOME_AGRUPADOR

FROM TGFFIN FIN
INNER JOIN TSIEMP EMP ON FIN.CODEMP = EMP.CODEMP
LEFT JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
LEFT JOIN TGFNAT NATPAI ON NAT.CODNATPAI = NATPAI.CODNAT
LEFT JOIN TGFNAT NATAVO ON NATPAI.CODNATPAI = NATAVO.CODNAT
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = FIN.CODCENCUS
LEFT JOIN TSICUS CUSPAI ON CUS.CODCENCUSPAI = CUSPAI.CODCENCUS
LEFT JOIN TSICUS CUSAVO ON CUSPAI.CODCENCUSPAI = CUSAVO.CODCENCUS
INNER JOIN AD_SQADRE CLAS ON CLAS.CODNAT = NAT.CODNAT

WHERE
FIN.ORIGEM IN ('F', 'P')
AND FIN.CODNAT NOT IN (SELECT CODNAT FROM AD_SQADRE WHERE ORDEM = 1)
AND FIN.RECDESP <> 0