CREATE OR REPLACE VIEW SQA_DRE_GERENCIAL AS
SELECT
ITE.NUNOTA
, CAB.NUMNOTA
, ITE.CODPROD
, PRO.CODGRUPOPROD
, CAB.DTNEG AS DTREF
, TO_CHAR(CAB.DTNEG,'MM') AS MES
, TO_CHAR(CAB.DTNEG,'YYYY') AS ANO
, CAB.CODEMP
, EMP.CODEMPMATRIZ
, CAB.CODTIPOPER
, CAB.CODCENCUS
, CUS.DESCRCENCUS
, CAB.CODNAT
, NAT.DESCRNAT
, CASE
     WHEN CAB.TIPMOV = 'V' THEN (CAB.VLRNOTA)
     WHEN CAB.TIPMOV = 'D' THEN (CAB.VLRNOTA) * -1
     WHEN CAB.TIPMOV = 'C' THEN (CAB.VLRNOTA) * -1
     WHEN CAB.TIPMOV = 'E' THEN (CAB.VLRNOTA)
END AS VALOR
, 'ESTOQUE' AS ORIGEM
, CLAS.ORDEM
, CLAS.CLASSIFICADOR AS NOME_CLASSIFICADOR

FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
LEFT JOIN TGFNAT NAT ON NAT.CODNAT = CAB.CODNAT
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = CAB.CODCENCUS
INNER JOIN AD_SQADRE CLAS ON CLAS.CODNAT = NAT.CODNAT

WHERE
CAB.STATUSNOTA = 'L'
AND CAB.TIPMOV IN ('V','D','E','C')

UNION ALL

SELECT
Z.NUNOTA
, Z.NUMNOTA
, Z.CODPROD
, Z.CODGRUPOPROD
, Z.DTNEG AS DTREF
, TO_CHAR(Z.DTNEG,'MM') AS MES
, TO_CHAR(Z.DTNEG,'YYYY') AS ANO
, Z.CODEMP
, Z.CODEMPMATRIZ
, Z.CODTIPOPER
, Z.CODCENCUS
, Z.DESCRCENCUS
, 30000000 AS CODNAT
, 'CMV ' AS DESCRNAT
, ROUND(SUM(CASE WHEN Z.TIPMOV = 'V' THEN CUSTOTOTAL * (-1) ELSE CUSTOTOTAL * (1) END), 2) AS VALOR
,'CUSTO' AS ORIGEM
, 3 AS ORDEM
, Z.CLASSIFICADOR AS NOME_CLASSIFICADOR

FROM (
   SELECT
       ITE.NUNOTA
       , CAB.NUMNOTA
       , ITE.CODPROD
       , PRO.CODGRUPOPROD
       , CAB.DTNEG
       , CAB.CODEMP
       , EMP.CODEMPMATRIZ
       , CAB.CODTIPOPER
       , CAB.CODNAT
       , CAB.CODCENCUS
       , CUS.DESCRCENCUS
       , CLAS.CLASSIFICADOR
       , CAB.TIPMOV
       , NVL((SELECT SUM(CUS.CUSSEMICM*ITE.QTDNEG)
                  FROM TGFCUS CUS
                  WHERE CUS.CODEMP = CAB.CODEMP
                    AND CUS.CODPROD = ITE.CODPROD
                    AND CUS.DTATUAL = (SELECT MAX(DTATUAL)
                                     FROM TGFCUS
                                     WHERE CODEMP = CUS.CODEMP
                                       AND CODPROD = CUS.CODPROD AND DTATUAL <= CAB.DTNEG)),0) AS CUSTOTOTAL

   FROM TGFCAB CAB
                   INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
                   INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
                   INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
                   INNER JOIN TGFTOP TPO ON CAB.CODTIPOPER = TPO.CODTIPOPER AND CAB.DHTIPOPER = TPO.DHALTER
                   LEFT JOIN  TSICUS CUS ON CUS.CODCENCUS = CAB.CODCENCUS
                   INNER JOIN AD_SQADRE CLAS ON CLAS.CODNAT = CAB.CODNAT

   WHERE CAB.STATUSNOTA = 'L'
     AND CAB.TIPMOV IN ('V','D')
    )Z

GROUP BY
Z.NUNOTA
, Z.NUMNOTA
, Z.CODPROD
, Z.CODGRUPOPROD
, Z.DTNEG
, TO_CHAR(Z.DTNEG,'MM')
, TO_CHAR(Z.DTNEG,'YYYY')
, Z.CODEMP
, Z.CODEMPMATRIZ
, Z.CODTIPOPER
, Z.CODCENCUS
, Z.DESCRCENCUS
, Z.CLASSIFICADOR

UNION ALL

SELECT
ITE.NUNOTA
, CAB.NUMNOTA
, ITE.CODPROD
, PRO.CODGRUPOPROD
, CAB.DTNEG AS DTREF
, TO_CHAR(CAB.DTNEG,'MM') AS MES
, TO_CHAR(CAB.DTNEG,'YYYY') AS ANO
, CAB.CODEMP
, EMP.CODEMPMATRIZ
, CAB.CODTIPOPER
, CAB.CODCENCUS
, CUS.DESCRCENCUS
, 40000000                   AS CODNAT
, 'IMPOSTOS SOBRE VENDAS'    AS DESCRNAT
, VALOR * -1                 AS VALOR
, 'IMPOSTOS'                 AS ORIGEM
, 2                          AS ORDEM
, (SELECT OPCAO FROM TDDOPC WHERE NUCAMPO = (SELECT NUCAMPO FROM TDDCAM WHERE NOMETAB = 'TGFDIN' AND NOMECAMPO = 'CODIMP') AND VALOR = DIN.CODIMP) AS NOME_CLASSIFICADOR

FROM TGFCAB CAB
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = CAB.CODCENCUS
INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFDIN DIN ON DIN.NUNOTA = ITE.NUNOTA AND DIN.SEQUENCIA = ITE.SEQUENCIA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFTOP TTP ON TTP.CODTIPOPER = CAB.CODTIPOPER AND TTP.DHALTER = CAB.DHTIPOPER
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP

WHERE
TTP.GOLSINAL = -1
AND TTP.GOLDEV = 1
AND CAB.STATUSNOTA = 'L'
AND CAB.TIPMOV IN ('V','D','E','C')
AND DIN.CODIMP IN (1,4,6,7)

UNION ALL

SELECT
FIN.NUFIN
, FIN.NUMNOTA
, 0 AS CODPROD
, 0 AS CODGRUPOPROD
, FIN.DTNEG AS DTREF
, TO_CHAR(FIN.DTNEG,'MM') AS MES
, TO_CHAR(FIN.DTNEG,'YYYY') AS ANO
, FIN.CODEMP
, EMP.CODEMPMATRIZ
, FIN.CODTIPOPER
, FIN.CODCENCUS
, CUS.DESCRCENCUS
, FIN.CODNAT
, NAT.DESCRNAT
, FIN.VLRDESDOB * FIN.RECDESP AS VALOR
, 'FINANCEIRO'                AS ORIGEM
, CLAS.ORDEM
, CLAS.CLASSIFICADOR          AS NOME_CLASSIFICADOR

FROM TGFFIN FIN
INNER JOIN TSIEMP EMP ON FIN.CODEMP = EMP.CODEMP
INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = FIN.CODCENCUS
INNER JOIN AD_SQADRE CLAS ON CLAS.CODNAT = NAT.CODNAT

WHERE
FIN.ORIGEM IN ('F', 'P')
AND FIN.RECDESP <> 0