WITH DADOS AS (SELECT
                   DRE.ORDEM
                    , DRE.NOME_CLASSIFICADOR
                    , CASE WHEN DRE.CODNAT = 40000000 THEN 40000000 WHEN DRE.CODNAT = 30000000 THEN 30000000 ELSE NAT3.CODNAT END AS CODNATPAI
                    , CASE WHEN DRE.CODNAT = 40000000 THEN 'IMPOSTOS SOBRE VENDAS' WHEN DRE.CODNAT = 30000000 THEN 'CMV' ELSE NAT3.DESCRNAT END AS DESCRNATPAI
                    , DRE.CODNAT
                    , CONCAT(DRE.CODNAT, ' - ', DRE.DESCRNAT) AS DESCRNAT
                    , SUM(CASE WHEN MES = 01 THEN DRE.VALOR END) AS JANEIRO
                    , SUM(CASE WHEN MES = 02 THEN DRE.VALOR END) AS FEVEREIRO
                    , SUM(CASE WHEN MES = 03 THEN DRE.VALOR END) AS MARCO
                    , SUM(CASE WHEN MES = 04 THEN DRE.VALOR END) AS ABRIL
                    , SUM(CASE WHEN MES = 05 THEN DRE.VALOR END) AS MAIO
                    , SUM(CASE WHEN MES = 06 THEN DRE.VALOR END) AS JUNHO
                    , SUM(CASE WHEN MES = 07 THEN DRE.VALOR END) AS JULHO
                    , SUM(CASE WHEN MES = 08 THEN DRE.VALOR END) AS AGOSTO
                    , SUM(CASE WHEN MES = 09 THEN DRE.VALOR END) AS SETEMBRO
                    , SUM(CASE WHEN MES = 10 THEN DRE.VALOR END) AS OUTUBRO
                    , SUM(CASE WHEN MES = 11 THEN DRE.VALOR END) AS NOVEMBRO
                    , SUM(CASE WHEN MES = 12 THEN DRE.VALOR END) AS DEZEMBRO
                    , SUM(DRE.VALOR) AS TOTAL
                    , SUM((DRE.VALOR)) / ((MONTH(:P_PERIODO.FIN) - MONTH (:P_PERIODO.INI)) + 1) AS MEDIA
                   /*, ABS((SELECT SUM(VALOR) / ((MONTH(:P_PERIODO.FIN) - MONTH (:P_PERIODO.INI)) + 1) FROM AD_SQA_DRE_GERENCIAL_ZP WHERE ORDEM IN (1,2)) * 100) AS AV_MEDIA*/

                   FROM AD_SQA_DRE_GERENCIAL_ZP DRE
                        LEFT JOIN TGFNAT NAT3 ON ROUND(DRE.CODNAT/10000, 0) *10000 = NAT3.CODNAT

               WHERE
                       DRE.CODEMP = :P_CODEMP
                 AND DRE.DTREF BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
                 AND ORIGEM NOT IN ('RATEIO')

               GROUP BY
                   DRE.ORDEM
                      , DRE.NOME_CLASSIFICADOR
                      , NAT3.CODNAT
                      , NAT3.DESCRNAT
                      , DRE.CODNAT
                      , DRE.DESCRNAT),

     CONTROLADORIA AS (SELECT
                           DRE.ORDEM
                            , DRE.NOME_CLASSIFICADOR
                            , NAT3.CODNAT AS CODNATPAI
                            , NAT3.DESCRNAT AS DESCRNATPAI
                            , DRE.CODNAT
                            , CONCAT(DRE.CODNAT, ' - ', DRE.DESCRNAT) AS DESCRNAT
                            , SUM(CASE WHEN MES = 01 THEN DRE.VALOR END) AS JANEIRO
                            , SUM(CASE WHEN MES = 02 THEN DRE.VALOR END) AS FEVEREIRO
                            , SUM(CASE WHEN MES = 03 THEN DRE.VALOR END) AS MARCO
                            , SUM(CASE WHEN MES = 04 THEN DRE.VALOR END) AS ABRIL
                            , SUM(CASE WHEN MES = 05 THEN DRE.VALOR END) AS MAIO
                            , SUM(CASE WHEN MES = 06 THEN DRE.VALOR END) AS JUNHO
                            , SUM(CASE WHEN MES = 07 THEN DRE.VALOR END) AS JULHO
                            , SUM(CASE WHEN MES = 08 THEN DRE.VALOR END) AS AGOSTO
                            , SUM(CASE WHEN MES = 09 THEN DRE.VALOR END) AS SETEMBRO
                            , SUM(CASE WHEN MES = 10 THEN DRE.VALOR END) AS OUTUBRO
                            , SUM(CASE WHEN MES = 11 THEN DRE.VALOR END) AS NOVEMBRO
                            , SUM(CASE WHEN MES = 12 THEN DRE.VALOR END) AS DEZEMBRO
                            , SUM(DRE.VALOR) AS TOTAL
                            , SUM((DRE.VALOR)) / ((MONTH(:P_PERIODO.FIN) - MONTH (:P_PERIODO.INI)) + 1) AS MEDIA
                           /*, ABS((SELECT SUM(VALOR) / ((MONTH(:P_PERIODO.FIN) - MONTH (:P_PERIODO.INI)) + 1) FROM AD_SQA_DRE_GERENCIAL_ZP WHERE ORDEM IN (1,2)) * 100) AS AV_MEDIA*/

                       FROM AD_SQA_DRE_GERENCIAL_ZP DRE
                                LEFT JOIN TGFNAT NAT3 ON ROUND(DRE.CODNAT/10000, 0) *10000 = NAT3.CODNAT

                       WHERE
                               DRE.CODEMP = :P_CODEMP
                         AND DRE.DTREF BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
                         AND ORIGEM IN ('RATEIO')

                       GROUP BY
                           DRE.ORDEM
                              , DRE.NOME_CLASSIFICADOR
                              , NAT3.CODNAT
                              , NAT3.DESCRNAT
                              , DRE.CODNAT
                              , DRE.DESCRNAT)

SELECT
    '#2a7344' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 10 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b> ( = ) RECEITA BRUTA <b>' AS DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA/MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 1

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 20 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 1
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 30 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b> DEDUÇÕES <b>' AS DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 2

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 40 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 2
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#2a7344' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 50 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b> ( = ) RECEITA LIQUIDA </b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (1,2)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 60 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 3
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#2a7344' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 70 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b> ( = ) RESULTADO BRUTO </b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (1,2,3)

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 80 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b>DESPESAS </b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (4, 5, 6, 7, 8, 9, 10, 11)

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 90 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -99999999 AS CODNAT
     , '<b>PESSOAL</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (4)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 100 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 4
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 110 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -99999999 AS CODNAT
     , '<b>ESTRUTURAL</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (5)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 120 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 5
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 130 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b>GERAL E USO CONSUMO </b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (6)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 140 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 6
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 150 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b>LOGISTICA</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (7)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 160 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 7
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 170 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -99999999 AS CODNAT
     , '<b>MARKETING</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (8)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 180 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 8
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 190 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -99999999 AS CODNAT
     , '<b>CSC</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (9)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 200 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 9
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 210 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -99999999 AS CODNAT
     , '<b>EXPANSAO</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (10)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 220 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 10
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 230 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -99999999 AS CODNAT
     , '<b>OBRAS</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (11)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 240 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 11
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#2a7344' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 250 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b> ( = ) RESULTADO OPERACIONAL </b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 260 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b>FINANCEIRAS</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (12)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 270 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 12
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 280 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b>OUTRAS DESPESA/RECEITAS</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (13, 14)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 290 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 13
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 300 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM = 14
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#2a7344' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 310 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b>( = ) RESULTADO ANTES DO IRPJ E CSLL</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 320 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '50000000 - PROVISAO IRPJ'
     , CASE WHEN ISNULL(SUM(JANEIRO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(JANEIRO),0) * 0.25 ELSE ISNULL(SUM(JANEIRO),0) * 0.15 END AS JANEIRO
     , CASE WHEN ISNULL(SUM(FEVEREIRO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(FEVEREIRO),0) * 0.25 ELSE ISNULL(SUM(FEVEREIRO),0) * 0.15 END AS FEVEREIRO
     , CASE WHEN ISNULL(SUM(MARCO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(MARCO),0) * 0.25 ELSE ISNULL(SUM(MARCO),0) * 0.15 END AS MARCO
     , CASE WHEN ISNULL(SUM(ABRIL),0) * 0.15 > 20000.00 THEN ISNULL(SUM(ABRIL),0) * 0.25 ELSE ISNULL(SUM(ABRIL),0) * 0.15 END AS ABRIL
     , CASE WHEN ISNULL(SUM(MAIO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(MAIO),0) * 0.25 ELSE ISNULL(SUM(MAIO),0) * 0.15 END AS MAIO
     , CASE WHEN ISNULL(SUM(JUNHO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(JUNHO),0) * 0.25 ELSE ISNULL(SUM(JUNHO),0) * 0.15 END AS JUNHO
     , CASE WHEN ISNULL(SUM(JULHO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(JULHO),0) * 0.25 ELSE ISNULL(SUM(JULHO),0) * 0.15 END AS JULHO
     , CASE WHEN ISNULL(SUM(AGOSTO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(AGOSTO),0) * 0.25 ELSE ISNULL(SUM(AGOSTO),0) * 0.15 END AS AGOSTO
     , CASE WHEN ISNULL(SUM(SETEMBRO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(SETEMBRO),0) * 0.25 ELSE ISNULL(SUM(SETEMBRO),0) * 0.15 END AS SETEMBRO
     , CASE WHEN ISNULL(SUM(OUTUBRO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(OUTUBRO),0) * 0.25 ELSE ISNULL(SUM(OUTUBRO),0) * 0.15 END AS OUTUBRO
     , CASE WHEN ISNULL(SUM(NOVEMBRO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(NOVEMBRO),0) * 0.25 ELSE ISNULL(SUM(NOVEMBRO),0) * 0.15 END AS NOVEMBRO
     , CASE WHEN ISNULL(SUM(DEZEMBRO),0) * 0.15 > 20000.00 THEN ISNULL(SUM(DEZEMBRO),0) * 0.25 ELSE ISNULL(SUM(DEZEMBRO),0) * 0.15 END AS DEZEMBRO
     , CASE WHEN ISNULL(SUM(TOTAL),0) * 0.15 > 20000.00 THEN ISNULL(SUM(TOTAL),0) * 0.25 ELSE ISNULL(SUM(TOTAL),0) * 0.15 END AS TOTAL
     , CASE WHEN ISNULL(SUM(MEDIA),0) * 0.15 > 20000.00 THEN ISNULL(SUM(MEDIA),0) * 0.25 ELSE ISNULL(SUM(MEDIA),0) * 0.15 END AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/

FROM DADOS
WHERE ORDEM IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 330 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '50000000 - PROVISAO CSLL '
     , ISNULL(SUM(JANEIRO),0) * 0.09 AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) * 0.09 AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) * 0.09 AS MARCO
     , ISNULL(SUM(ABRIL),0) * 0.09 AS ABRIL
     , ISNULL(SUM(MAIO),0) * 0.09 AS MAIO
     , ISNULL(SUM(JUNHO),0) * 0.09 AS JUNHO
     , ISNULL(SUM(JULHO),0) * 0.09 AS JULHO
     , ISNULL(SUM(AGOSTO),0) * 0.09 AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) * 0.09 AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) * 0.09 AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) * 0.09 AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) * 0.09 AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) * 0.09 AS DEZEMBRO
     , ISNULL(SUM(MEDIA),0) * 0.09 AS DEZEMBRO
    /*, SUM(AV_MEDIA) *0.09 AS AV_MEDIA*/
FROM DADOS
WHERE ORDEM IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)


UNION ALL

SELECT
    '#2a7344' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 340 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b>( = ) RESULTADO PÓS IRPJ E CSLL</b>'
     , CASE WHEN ISNULL(SUM(JANEIRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(JANEIRO) - (SUM(JANEIRO) * 0.34)),0) ELSE ISNULL((SUM(JANEIRO) - (SUM(JANEIRO) * 0.24)),0) END AS JANEIRO
     , CASE WHEN ISNULL(SUM(FEVEREIRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(FEVEREIRO) - (SUM(FEVEREIRO) * 0.34)),0) ELSE ISNULL((SUM(FEVEREIRO) - (SUM(FEVEREIRO) * 0.24)),0) END AS FEVEREIRO
     , CASE WHEN ISNULL(SUM(MARCO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(MARCO) - (SUM(MARCO) * 0.34)),0) ELSE ISNULL((SUM(MARCO) - (SUM(MARCO) * 0.24)),0) END AS MARCO
     , CASE WHEN ISNULL(SUM(ABRIL),0) * 0.15 > 20000.00 THEN ISNULL((SUM(ABRIL) - (SUM(ABRIL) * 0.34)),0) ELSE ISNULL((SUM(ABRIL) - (SUM(ABRIL) * 0.24)),0) END AS ABRIL
     , CASE WHEN ISNULL(SUM(MAIO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(MAIO) - (SUM(MAIO) * 0.34)),0) ELSE ISNULL((SUM(MAIO) - (SUM(MAIO) * 0.24)),0) END AS MAIO
     , CASE WHEN ISNULL(SUM(JUNHO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(JUNHO) - (SUM(JUNHO) * 0.34)),0) ELSE ISNULL((SUM(JUNHO) - (SUM(JUNHO) * 0.24)),0) END AS JUNHO
     , CASE WHEN ISNULL(SUM(JULHO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(JULHO) - (SUM(JULHO) * 0.34)),0) ELSE ISNULL((SUM(JULHO) - (SUM(JULHO) * 0.24)),0) END AS JULHO
     , CASE WHEN ISNULL(SUM(AGOSTO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(AGOSTO) - (SUM(AGOSTO) * 0.34)),0) ELSE ISNULL((SUM(AGOSTO) - (SUM(AGOSTO) * 0.24)),0) END AS AGOSTO
     , CASE WHEN ISNULL(SUM(SETEMBRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(SETEMBRO) - (SUM(SETEMBRO) * 0.34)),0) ELSE ISNULL((SUM(SETEMBRO) - (SUM(SETEMBRO) * 0.24)),0) END AS SETEMBRO
     , CASE WHEN ISNULL(SUM(OUTUBRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(OUTUBRO) - (SUM(OUTUBRO) * 0.34)),0) ELSE ISNULL((SUM(OUTUBRO) - (SUM(OUTUBRO) * 0.24)),0) END AS OUTUBRO
     , CASE WHEN ISNULL(SUM(NOVEMBRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(NOVEMBRO) - (SUM(NOVEMBRO) * 0.34)),0) ELSE ISNULL((SUM(NOVEMBRO) - (SUM(NOVEMBRO) * 0.24)),0) END AS NOVEMBRO
     , CASE WHEN ISNULL(SUM(DEZEMBRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(DEZEMBRO) - (SUM(DEZEMBRO) * 0.34)),0) ELSE ISNULL((SUM(DEZEMBRO) - (SUM(DEZEMBRO) * 0.24)),0) END AS DEZEMBRO
     , CASE WHEN ISNULL(SUM(TOTAL),0) * 0.15 > 20000.00 THEN ISNULL((SUM(TOTAL) - (SUM(TOTAL) * 0.34)),0) ELSE ISNULL((SUM(TOTAL) - (SUM(TOTAL) * 0.24)),0) END AS TOTAL
     , CASE WHEN ISNULL(SUM(MEDIA),0) * 0.15 > 20000.00 THEN ISNULL((SUM(MEDIA) - (SUM(MEDIA) * 0.34)),0) ELSE ISNULL((SUM(MEDIA) - (SUM(MEDIA) * 0.24)),0) END AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/

FROM DADOS
WHERE ORDEM IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 350 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b>( + ) ADICAO</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM CONTROLADORIA
WHERE ORDEM IN (2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14) AND :P_FLAG = 'S'

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 360 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM CONTROLADORIA
WHERE ORDEM IN (2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14) AND :P_FLAG = 'S'
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#06973a' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 370 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b>( - ) EXCLUSAO</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM CONTROLADORIA
WHERE ORDEM IN (1) AND :P_FLAG = 'S'

UNION ALL

SELECT
    '#f9f9f9' AS BKCOLOR
     ,'#000000' AS FGCOLOR
     , 380 AS SEQUENCIA
     , CODNATPAI
     , DESCRNATPAI
     , CODNAT
     , DESCRNAT
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
    /*, SUM(AV_MEDIA) AS AV_MEDIA*/
FROM CONTROLADORIA
WHERE ORDEM IN (1) AND :P_FLAG = 'S'
GROUP BY CODNAT, DESCRNAT, CODNATPAI, DESCRNATPAI

UNION ALL

SELECT
    '#2a7344' AS BKCOLOR
     , '#f9f9f9' AS FGCOLOR
     , 390 AS SEQUENCIA
     , 0 AS CODNATPAI
     , '' AS DESCRNATPAI
     , -999999 AS CODNAT
     , '<b>( = ) RESULTADO GERENCIAL</b>'
     , ISNULL(SUM(JANEIRO),0) AS JANEIRO
     , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
     , ISNULL(SUM(MARCO),0) AS MARCO
     , ISNULL(SUM(ABRIL),0) AS ABRIL
     , ISNULL(SUM(MAIO),0) AS MAIO
     , ISNULL(SUM(JUNHO),0) AS JUNHO
     , ISNULL(SUM(JULHO),0) AS JULHO
     , ISNULL(SUM(AGOSTO),0) AS AGOSTO
     , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
     , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
     , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
     , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
     , ISNULL(SUM(TOTAL),0) AS TOTAL
     , ISNULL(SUM(MEDIA),0) AS MEDIA
FROM
    (

        SELECT
            CASE WHEN ISNULL(SUM(JANEIRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(JANEIRO) - (SUM(JANEIRO) * 0.34)),0) ELSE ISNULL((SUM(JANEIRO) - (SUM(JANEIRO) * 0.24)),0) END AS JANEIRO
             , CASE WHEN ISNULL(SUM(FEVEREIRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(FEVEREIRO) - (SUM(FEVEREIRO) * 0.34)),0) ELSE ISNULL((SUM(FEVEREIRO) - (SUM(FEVEREIRO) * 0.24)),0) END AS FEVEREIRO
             , CASE WHEN ISNULL(SUM(MARCO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(MARCO) - (SUM(MARCO) * 0.34)),0) ELSE ISNULL((SUM(MARCO) - (SUM(MARCO) * 0.24)),0) END AS MARCO
             , CASE WHEN ISNULL(SUM(ABRIL),0) * 0.15 > 20000.00 THEN ISNULL((SUM(ABRIL) - (SUM(ABRIL) * 0.34)),0) ELSE ISNULL((SUM(ABRIL) - (SUM(ABRIL) * 0.24)),0) END AS ABRIL
             , CASE WHEN ISNULL(SUM(MAIO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(MAIO) - (SUM(MAIO) * 0.34)),0) ELSE ISNULL((SUM(MAIO) - (SUM(MAIO) * 0.24)),0) END AS MAIO
             , CASE WHEN ISNULL(SUM(JUNHO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(JUNHO) - (SUM(JUNHO) * 0.34)),0) ELSE ISNULL((SUM(JUNHO) - (SUM(JUNHO) * 0.24)),0) END AS JUNHO
             , CASE WHEN ISNULL(SUM(JULHO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(JULHO) - (SUM(JULHO) * 0.34)),0) ELSE ISNULL((SUM(JULHO) - (SUM(JULHO) * 0.24)),0) END AS JULHO
             , CASE WHEN ISNULL(SUM(AGOSTO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(AGOSTO) - (SUM(AGOSTO) * 0.34)),0) ELSE ISNULL((SUM(AGOSTO) - (SUM(AGOSTO) * 0.24)),0) END AS AGOSTO
             , CASE WHEN ISNULL(SUM(SETEMBRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(SETEMBRO) - (SUM(SETEMBRO) * 0.34)),0) ELSE ISNULL((SUM(SETEMBRO) - (SUM(SETEMBRO) * 0.24)),0) END AS SETEMBRO
             , CASE WHEN ISNULL(SUM(OUTUBRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(OUTUBRO) - (SUM(OUTUBRO) * 0.34)),0) ELSE ISNULL((SUM(OUTUBRO) - (SUM(OUTUBRO) * 0.24)),0) END AS OUTUBRO
             , CASE WHEN ISNULL(SUM(NOVEMBRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(NOVEMBRO) - (SUM(NOVEMBRO) * 0.34)),0) ELSE ISNULL((SUM(NOVEMBRO) - (SUM(NOVEMBRO) * 0.24)),0) END AS NOVEMBRO
             , CASE WHEN ISNULL(SUM(DEZEMBRO),0) * 0.15 > 20000.00 THEN ISNULL((SUM(DEZEMBRO) - (SUM(DEZEMBRO) * 0.34)),0) ELSE ISNULL((SUM(DEZEMBRO) - (SUM(DEZEMBRO) * 0.24)),0) END AS DEZEMBRO
             , CASE WHEN ISNULL(SUM(TOTAL),0) * 0.15 > 20000.00 THEN ISNULL((SUM(TOTAL) - (SUM(TOTAL) * 0.34)),0) ELSE ISNULL((SUM(TOTAL) - (SUM(TOTAL) * 0.24)),0) END AS TOTAL
             , CASE WHEN ISNULL(SUM(MEDIA),0) * 0.15 > 20000.00 THEN ISNULL((SUM(MEDIA) - (SUM(MEDIA) * 0.34)),0) ELSE ISNULL((SUM(MEDIA) - (SUM(MEDIA) * 0.24)),0) END AS MEDIA
            /*, SUM(AV_MEDIA) AS MEDIA*/

        FROM DADOS
        WHERE ORDEM IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)

        UNION ALL

        SELECT
            ISNULL(SUM(JANEIRO),0) AS JANEIRO
             , ISNULL(SUM(FEVEREIRO),0) AS FEVEREIRO
             , ISNULL(SUM(MARCO),0) AS MARCO
             , ISNULL(SUM(ABRIL),0) AS ABRIL
             , ISNULL(SUM(MAIO),0) AS MAIO
             , ISNULL(SUM(JUNHO),0) AS JUNHO
             , ISNULL(SUM(JULHO),0) AS JULHO
             , ISNULL(SUM(AGOSTO),0) AS AGOSTO
             , ISNULL(SUM(SETEMBRO),0) AS SETEMBRO
             , ISNULL(SUM(OUTUBRO),0) AS OUTUBRO
             , ISNULL(SUM(NOVEMBRO),0) AS NOVEMBRO
             , ISNULL(SUM(DEZEMBRO),0) AS DEZEMBRO
             , ISNULL(SUM(TOTAL),0) AS TOTAL
             , ISNULL(SUM(MEDIA),0) AS MEDIA
            /*, SUM(AV_MEDIA) AS AV_MEDIA*/
        FROM CONTROLADORIA
        WHERE ORDEM IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)
        AND :P_FLAG = 'S'
    )Z


ORDER BY 3, 6