CREATE OR REPLACE FUNCTION HT_SALDO_INICIAL( P_CODEMP INT, P_CODPROD INT, P_DTREFERENCIA DATE )
RETURN NUMBER IS
   P_SALDO_INICIAL   NUMBER;

BEGIN


    SELECT SUM(Z.ESTOQUE) INTO P_SALDO_INICIAL FROM
        (SELECT
             NVL(ESTOQUE,0) AS ESTOQUE
         FROM TGFEST

         WHERE
                 CODPROD = P_CODPROD
           AND CODEMP = P_CODEMP
           AND TIPO = 'P'

         UNION ALL

         SELECT
             (SUM (CASE WHEN TTP.ATUALEST = 'B' THEN NVL(ITE.QTDNEG,0) * (1) END) + SUM(CASE WHEN TTP.ATUALEST = 'E' THEN NVL(ITE.QTDNEG,0) * (-1) END)) AS MOVIMENTO
         FROM TGFCAB CAB
                  INNER JOIN TGFTOP TTP ON TTP.CODTIPOPER = CAB.CODTIPOPER AND TTP.DHALTER = CAB.DHTIPOPER
                  INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA

         WHERE ITE.CODPROD = P_CODPROD
           AND CAB.CODEMP = P_CODEMP
           AND CAB.DTENTSAI >= P_DTREFERENCIA
           AND CAB.TIPMOV IN ('V','D','E','C')
           AND TTP.ATUALEST IN ('B','E')
        )Z;

    RETURN P_SALDO_INICIAL;

END;

--     SELECT HT_SALDO_INICIAL(2,3987,'01/01/2022') FROM  DUAL
