CREATE OR REPLACE VIEW SQA_DADOS_GERENCIAL AS
SELECT
    CAB.CODEMP
     , EMP.RAZAOSOCIAL
     , ITE.NUNOTA
     , CAB.NUMNOTA
     , CAB.STATUSNOTA
     , CAB.STATUSNFE
     , CAB.CODPARC
     , PAR.NOMEPARC
     , PAR.CODCID
     , CID.NOMECID
     , PAR.CODREG
     , REG.NOMEREG
     , REGPAI.CODREG AS CODREG_PAI
     , REGPAI.NOMEREG AS NOMEREG_PAI
     , CAB.CODVEND
     , VEN.APELIDO
     , CASE WHEN PAR.TIPPESSOA = 'F' THEN 'FISICA' ELSE 'JURIDICA' END AS TIPPESSOA
     , CAB.DTNEG
     , CAB.DTENTSAI
     , CAB.DTMOV
     , CAB.CODNAT
     , NAT.DESCRNAT
     , NATPAI.CODNAT AS CODNAT_PAI
     , NATPAI.DESCRNAT AS DESCRNAT_PAI
     , NATAVO.CODNAT AS CODNAT_AVO
     , NATAVO.DESCRNAT AS DESCRNAT_AVO
     , CAB.CODCENCUS
     , CUS.DESCRCENCUS
     , CUSPAI.CODCENCUS AS CODCENCUS_PAI
     , CUSPAI.DESCRCENCUS AS DESCRCENCUS_PAI
     , CUSAVO.CODCENCUS AS CODCENCUS_AVO
     , CUSAVO.DESCRCENCUS AS DESCRCENCUS_AVO
     , CAB.CODPROJ
     , PRJ.IDENTIFICACAO
     , CAB.CODTIPOPER
     , TTP.DESCROPER
     , CAB.TIPMOV
     , ITE.CODPROD
     , PRO.DESCRPROD
     , PRO.CODGRUPOPROD
     , GRU.DESCRGRUPOPROD
     , GRUPAI.CODGRUPOPROD AS CODGRUPOPROD_PAI
     , GRUPAI.DESCRGRUPOPROD AS DESCRGRUPOPROD_PAI
     , GRUAVO.CODGRUPOPROD AS CODGRUPOPROD_AVO
     , GRUAVO.DESCRGRUPOPROD AS DESCRGRUPOPROD_AVO
     , GRUBIS.CODGRUPOPROD AS CODGRUPOPROD_BIS
     , GRUBIS.DESCRGRUPOPROD AS DESCRGRUPOPROD_BIS
     , CASE
            WHEN CAB.TIPMOV = 'V' THEN ITE.QTDNEG * (1)
            WHEN CAB.TIPMOV = 'D' THEN ITE.QTDNEG * (-1)
            WHEN CAB.TIPMOV = 'C' THEN ITE.QTDNEG * (-1)
            WHEN CAB.TIPMOV = 'E' THEN ITE.QTDNEG * (1)
      ELSE 0 END AS QTDNEG
     , CASE
            WHEN CAB.TIPMOV = 'V' THEN (ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * (1)
            WHEN CAB.TIPMOV = 'D' THEN (ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * (-1)
            WHEN CAB.TIPMOV = 'C' THEN (ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * (-1)
            WHEN CAB.TIPMOV = 'E' THEN (ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * (1)
      ELSE 0 END AS VLRTOTITEM
     , CASE
            WHEN CAB.TIPMOV = 'V' THEN (SELECT CUS.CUSREP * ITE.QTDNEG FROM TGFCUS CUS WHERE CUS.CODEMP = CAB.CODEMP AND CUS.CODPROD = ITE.CODPROD AND DTATUAL = (SELECT MAX(C.DTATUAL) FROM TGFCUS C WHERE C.CODEMP = CUS.CODEMP AND C.CODPROD = CUS.CODPROD AND C.DTATUAL <= CAB.DTNEG)) * (1)
            WHEN CAB.TIPMOV = 'D' THEN (SELECT CUS.CUSREP * ITE.QTDNEG FROM TGFCUS CUS WHERE CUS.CODEMP = CAB.CODEMP AND CUS.CODPROD = ITE.CODPROD AND DTATUAL = (SELECT MAX(C.DTATUAL) FROM TGFCUS C WHERE C.CODEMP = CUS.CODEMP AND C.CODPROD = CUS.CODPROD AND C.DTATUAL <= CAB.DTNEG)) * (-1)
      ELSE 0 END AS CUSTO

FROM TGFCAB CAB
         INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
         INNER JOIN TGFTOP TTP ON TTP.CODTIPOPER = CAB.CODTIPOPER AND TTP.DHALTER = CAB.DHTIPOPER
         INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
         INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
         INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
         INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
         INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
         LEFT JOIN TGFGRU GRUPAI ON TRUNC(GRU.CODGRUPOPROD, - 2) = GRUPAI.CODGRUPOPROD
         LEFT JOIN TGFGRU GRUAVO ON TRUNC(GRU.CODGRUPOPROD, - 4) = GRUAVO.CODGRUPOPROD
         LEFT JOIN TGFGRU GRUBIS ON TRUNC(GRU.CODGRUPOPROD, - 6) = GRUBIS.CODGRUPOPROD
         LEFT JOIN TGFNAT NAT ON NAT.CODNAT = CAB.CODNAT
         LEFT JOIN TGFNAT NATPAI ON TRUNC(NAT.CODNAT, - 2) = NATPAI.CODNAT
         LEFT JOIN TGFNAT NATAVO ON TRUNC(NAT.CODNAT, - 4) = NATAVO.CODNAT
         LEFT JOIN TCSPRJ PRJ ON CAB.CODPROJ = PRJ.CODPROJ
         LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = CAB.CODCENCUS
         LEFT JOIN TSICUS CUSPAI ON TRUNC(CUS.CODCENCUS, - 2) = CUSPAI.CODCENCUS
         LEFT JOIN TSICUS CUSAVO ON TRUNC(CUS.CODCENCUS, - 4) = CUSAVO.CODCENCUS
         LEFT JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND
         LEFT JOIN TSIREG REG ON PAR.CODREG = REG.CODREG
         LEFT JOIN TSIREG REGPAI ON REG.CODREGPAI = REGPAI.CODREG

WHERE
    CAB.TIPMOV IN ('V','D','E','C')
    AND CAB.STATUSNOTA = 'L'