SELECT C.CODIGO AS NROUNICOUSE-- BASE PARA O NUNOTA, CODIGO ÚNICO PARA IDENTIFICAR A VENDA
     , REPLACE(REPLACE(REPLACE(P.CPF,'.',''),'-',''),'/','') AS CPF_CLIENTE -- CONSULTAR NA TGFPAR SE EXISTE
     , C.DATA AS DTNEG
     , C.NOTA AS NUMNOTA
     , M.SERIENF AS SERIENOTA
     , ISNULL(ISNULL(M.VALORTOTALNOTA,C.TOTALPRODUTOS),0) AS VLRNOTA
     , ISNULL(M.CHAVENFE,C.CHAVENFE) AS CHAVENFE
     , CASE WHEN ISNULL(M.TIPOFRETE,M2.TIPOFRETE) = 9 THEN 'S' ELSE 'C' END AS CIF_FOB
     , CASE WHEN ISNULL(M.STATUSNFE,M2.STATUSNFE) = 3 THEN 'A' END AS STATUSNFE
     , ISNULL(M.PROTOCOLOAUTO,M2.PROTOCOLOAUTO) AS NUMPROTOC
     , ISNULL(ISNULL(M.BASEICMS,M2.BASEICMS),0) AS BASEICMS
     , ISNULL(ISNULL(M.VALORICMS,M2.VALORICMS),0) AS VLRICMS
     , ISNULL(ISNULL(M.BASEICMSSUBST,M2.BASEICMSSUBST),0) AS BASESUBSTIT
     , ISNULL(ISNULL(M.VALORICMSSUBST,M2.VALORICMSSUBST),0) AS VLRSUBST
     , ISNULL(ISNULL(M.VALORSEGURO,M2.VALORSEGURO),0) AS VLRSEG
     , ISNULL(ISNULL(M.VALOROUTRAS,M2.VALOROUTRAS),0) AS VLROUTROS
     , CASE WHEN ISNULL(M.VALORIPI,M2.VALORIPI) > 0 THEN ISNULL(M.BASEICMS,M2.BASEICMS) ELSE 0 END AS BASEIPI
     , ISNULL(ISNULL(M.VALORIPI,M2.VALORIPI),0) AS VLRIPI
     , ISNULL(ISNULL(M.TOTALFRETE,M2.TOTALFRETE),0) AS VLRFRETE
     , ISNULL(ISNULL(M.BASEICMSFRETE,M2.BASEICMSFRETE),0) AS BASEICMSFRETE
     , ISNULL(ISNULL(M.VALORICMSFRETE,M2.VALORICMSFRETE),0) AS ICMSFRETE
     , ISNULL(ISNULL(M.DESCONTOTALNOTA,M2.DESCONTOTALNOTA),0) AS VLRDESCTOTITEM
     , L.CODEMP AS CODEMP
     , 0 AS CODUSU
     , CASE WHEN ISNULL(M.MODELONF,M2.MODELONF) = 65 THEN 3290 ELSE 3289 END AS CODTIPOPER
     , 5 AS CODTIPVENDA
     , 0 AS CODCENCUS
     , 10010102 AS CODNAT
     , ISNULL(ISNULL(M.MODELONF,M2.MODELONF),0) AS MODELONF
     , L.CODPARC AS CODPARCLOJA
     , ISNULL(ISNULL(M.VICMSUFDEST,M2.VICMSUFDEST),0) AS VLRICMSDIFALDEST
     , ISNULL(ISNULL(M.VICMSUFREMET,M2.VICMSUFREMET),0) AS VLRICMSDIFALREM
FROM USE_VENDA C
         INNER JOIN AD_TGFLOJA L ON C.LOJA = L.CODLOJA
    -- LEFT JOIN USE_MOVIMENTOESTSAI M ON C.CODIGO = M.VENDA AND C.LOJA = M.LOJAEMI AND M.STATUSNFE = 3 AND C.NOTA = M.NOTA
         LEFT JOIN USE_MOVIMENTOESTSAI M ON ISNULL(C.CODIGOANTERIOR,C.CODIGO) = M.VENDA AND C.LOJA = M.LOJAEMI AND ISNULL(M.STATUSNFE,3) = 3 AND C.NOTA = M.NOTA
         LEFT JOIN USE_MOVIMENTOESTSAI M2 ON C.CHAVENFE = M2.CHAVENFE AND C.LOJA = M2.LOJAEMI AND ISNULL(M2.STATUSNFE,3) = 3 AND C.NOTA = M2.NOTA
         LEFT JOIN USE_CLIENTE P ON C.CLIENTE = P.CODIGO
WHERE /*L.ATIVO = 'S'
	   AND*/ L.CODFRANQ = 1 -- LOJAS PROPRIAS
  AND C.DATAEXC IS NULL
  AND ISNULL(M.CHAVENFE,C.CHAVENFE) IS NOT NULL
  AND C.CODIGO NOT IN (SELECT ISNULL(NUMCF,0) FROM TGFCAB WHERE CODTIPOPER IN(3289,3290) AND DTNEG = C.DATA AND CODEMP = L.CODEMP)
  AND C.CODIGO = @P_NROUNICOUSE