CREATE OR REPLACE VIEW HVL_DADOS_MOVIMENTO AS
(
SELECT
    Z.*
    , NVL(LAG(Z.QTDNEG) OVER (PARTITION BY Z.CODEMP, Z.CODPROD ORDER BY Z.DTENTSAI),0) AS QUANTIDADE_ANTERIOR
    , SUM(Z.QTDNEG * Z.ATUALESTOQUE) OVER (PARTITION BY Z.CODEMP, Z.CODPROD ORDER BY Z.DTENTSAI) AS ESTOQUE_ACUMULADO

FROM
    (SELECT CAB.CODEMP
         , NVL(CAB.HRENTSAI, CAB.DTENTSAI) AS DTENTSAI
         , CAB.NUNOTA
         , CAB.NUMNOTA
         , CAB.CODPARC
         , CAB.CHAVENFE
         , CAB.CODTIPOPER
         , ITE.ATUALESTOQUE
         , ITE.CODTRIB
         , ITE.CODCFO
         , ITE.CODPROD
         , PRO.DESCRPROD
         , ITE.QTDNEG
         , ITE.VLRUNIT
         , ITE.VLRTOT
         , ITE.VLRICMS
         , ITE.VLRSUBST
         , ITE.VLRSUBSTANT

    FROM TGFCAB CAB
             INNER JOIN TGFTOP TTP ON TTP.CODTIPOPER = CAB.CODTIPOPER AND TTP.DHALTER = CAB.DHTIPOPER
             INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
             INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD

    WHERE CAB.TIPMOV IN ('V', 'D', 'E', 'C')
      AND TTP.ATUALEST IN ('B', 'E')
      AND CAB.STATUSNOTA = 'L'
      )Z
)