-- AINDA NÃO SERÁ USADO UMA PROCEDURE

-- Essa consulta utiliza o subselect NOT EXISTS para verificar se já existe uma combinação de CODEMP, NUNOTA e NUMNOTA na tabela HVL_MOVIMENTO_ESTOQUE, se não existir ela faz o insert.
-- Aqui é importante notar que essa é uma das formas de evitar inserção de dados duplicados, mas existem outras alternativas, como usar a cláusula "on conflict" ou "merge" que já mencionei anteriormente.

INSERT INTO HVL_MOVIMENTO_ESTOQUE (CODEMP, DTENTSAI, NUNOTA, NUMNOTA, CODPARC, CHAVENFE, CODTIPOPER, ATUALESTOQUE, CODTRIB, CODCFO, CODPROD, DESCRPROD, QTDNEG, VLRUNIT, VLRTOT, VLRICMS, VLRSUBST, VLRSUBSTANT, QTD_ANTERIOR, ESTOQUE_ACUMULADO)
SELECT CODEMP, DTENTSAI, NUNOTA, NUMNOTA, CODPARC, CHAVENFE, CODTIPOPER, ATUALESTOQUE, CODTRIB, CODCFO, CODPROD, DESCRPROD, QTDNEG, VLRUNIT, VLRTOT, NVL(VLRICMS,0), NVL(VLRSUBST,0), NVL(VLRSUBSTANT,0), QUANTIDADE_ANTERIOR, ESTOQUE_ACUMULADO
FROM HVL_DADOS_MOVIMENTO
WHERE NOT EXISTS (SELECT 1 FROM HVL_MOVIMENTO_ESTOQUE WHERE HVL_MOVIMENTO_ESTOQUE.CODEMP = HVL_DADOS_MOVIMENTO.CODEMP
                                                        AND HVL_MOVIMENTO_ESTOQUE.NUNOTA = HVL_DADOS_MOVIMENTO.NUNOTA
                                                        AND HVL_MOVIMENTO_ESTOQUE.NUMNOTA = HVL_DADOS_MOVIMENTO.NUMNOTA)
