SELECT CODPROD
     , CODEMP
     , QTDNEG
     , VLRTOT
     , MAX(DTENTSAI)

     into v_CODPROD, v_CODEMP, v_QTDNEG, v_VLRTOT, v_DATA

FROM HVL_MOVIMENTO_ESTOQUE EST

WHERE EST.CODPROD = :v_CODPROD
  AND EST.CODEMP = :v_CODPROD
  AND EST.DTENTSAI <= (SELECT MIN(DTENTSAI)
                       FROM HVL_MOVIMENTO_ESTOQUE
                       WHERE CODEMP = EST.CODEMP
                         AND CODPROD = EST.CODPROD
                         AND ESTOQUE_ACUMULADO = 0
                         AND DTENTSAI > v_DATA)
GROUP BY CODPROD
     , CODEMP
     , QTDNEG
     , VLRTOT

-- A LÓGICA É QUE TODA VEZ QUE RODAR O LOOP A INFORMAÇÃO QUE VIER LA NA CONSULTA MAX(DTENTSAI) VEM PARA O WHERE DA SUBCONSULTA
-- E COM ESSES DADOS VAI SENDO TRABALHADO O VALOR MÉDIO PONDERADO PARA RESSARCIMENTO