SELECT
    CODNAT AS CODNAT
     , DESCRNAT AS DESCRNAT
     , SUM(CASE WHEN MONTH(DTNEG) = 01 THEN  VALOR ELSE 0 END) AS JANEIRO
     , SUM(CASE WHEN MONTH(DTNEG) = 02 THEN  VALOR ELSE 0 END) AS FEVEREIRO
     , SUM(CASE WHEN MONTH(DTNEG) = 03 THEN  VALOR ELSE 0 END) AS MARCO
     , SUM(CASE WHEN MONTH(DTNEG) = 04 THEN  VALOR ELSE 0 END) AS ABRIL
     , SUM(CASE WHEN MONTH(DTNEG) = 05 THEN  VALOR ELSE 0 END) AS MAIO
     , SUM(CASE WHEN MONTH(DTNEG) = 06 THEN  VALOR ELSE 0 END) AS JUNHO
     , SUM(CASE WHEN MONTH(DTNEG) = 07 THEN  VALOR ELSE 0 END) AS JULHO
     , SUM(CASE WHEN MONTH(DTNEG) = 08 THEN  VALOR ELSE 0 END) AS AGOSTO
     , SUM(CASE WHEN MONTH(DTNEG) = 09 THEN  VALOR ELSE 0 END) AS SETEMBRO
     , SUM(CASE WHEN MONTH(DTNEG) = 10 THEN  VALOR ELSE 0 END) AS OUTUBRO
     , SUM(CASE WHEN MONTH(DTNEG) = 11 THEN  VALOR ELSE 0 END) AS NOVEMBRO
     , SUM(CASE WHEN MONTH(DTNEG) = 12 THEN  VALOR ELSE 0 END) AS DEZEMBRO
     , SUM(VALOR) AS TOTAL
     , SUM((VALOR) ) / ((MONTH(:P_PERIODO.FIN) - MONTH(:P_PERIODO.INI))+1) AS MEDIA

FROM CND_SQA_DRE_GER

WHERE
    DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
  AND CODCENCUS IN :P_CODCENCUS
  AND CODEMP IN :P_CODEMP
  AND CODNATPAI = :A_CODNAT

GROUP BY CODNAT, DESCRNAT

ORDER BY 1