SELECT
    CODNAT AS CODNAT
     , DESCRNAT AS DESCRNAT
     , ABS(SUM(VALOR)) AS VALOR
     , MONTH(DTNEG) AS MES

FROM CND_SQA_DRE_GER

WHERE
    DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
  AND CODCENCUS IN :P_CODCENCUS
  AND CODEMP IN :P_CODEMP
  AND CODNAT = :A_CODNATFILHA

GROUP BY CODNAT, DESCRNAT, MONTH(DTNEG)

ORDER BY MONTH(DTNEG)