SELECT
    A.CODEMP
     , MONTH(A.DTNEG) AS MES
     , A.NUNOTA
     , A.NUMNOTA
     , A.DTNEG
     , A.CODPARC
     , A.RAZAOSOCIAL
     , A.CODTIPOPER
     , (SELECT DESCROPER FROM TGFTOP TTP WHERE TTP.CODTIPOPER = A.CODTIPOPER AND TTP.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP T WHERE T.CODTIPOPER = TTP.CODTIPOPER)) AS DESCROPER
     , A.CODCENCUS
     , (SELECT DESCRCENCUS FROM TSICUS CUS WHERE CUS.CODCENCUS = A.CODCENCUS) AS DESCRCENCUS
     , A.CODNAT
     , A.DESCRNAT
     , A.VALOR

FROM CND_SQA_DRE_GER A

WHERE
    DTNEG BETWEEN :P_PERIODO.INI and :P_PERIODO.FIN
  AND CODCENCUS IN :P_CODCENCUS
  AND CODEMP IN :P_CODEMP
  AND CODNAT = :A_CODNAT
  AND MONTH(DTNEG) = :A_MES

ORDER BY A.RAZAOSOCIAL ASC, A.VALOR DESC