SELECT FIN.DTNEG                        AS DTREF
     , FIN.NUFIN
     , FIN.NUMNOTA
     , FIN.CODPARC
     , PAR.RAZAOSOCIAL
     , FIN.DTNEG
     , MONTH(FIN.DTNEG) AS MES
     , YEAR(FIN.DTNEG) AS ANO
     , FIN.CODEMP
     , FIN.CODTIPOPER
     , TTP.DESCROPER
     , FIN.CODCENCUS
     , CUS.DESCRCENCUS
     , CUSPAI.CODCENCUS                 AS CODCENCUSPAI
     , CUSPAI.DESCRCENCUS               AS DESCRCENCUSPAI
     , CUSAVO.CODCENCUS                 AS CODCENCUSAVO
     , CUSAVO.DESCRCENCUS               AS DESCRCENCUSAVO
     , FIN.CODNAT
     , NAT.DESCRNAT
     , PAI.CODNAT                       AS CODNATPAI
     , PAI.DESCRNAT                     AS DESCRNATPAI
     , AVO.CODNAT                       AS CODNATAVO
     , AVO.DESCRNAT                     AS DESCRNATAVO
     , SUM(FIN.VLRDESDOB) * FIN.RECDESP AS VALOR
     , 'FINANCEIRO'                     AS ORIGEM
     , CLAS.ORDEM                                             -- PARA ORDERNAR
     , CLAS.CLASSIFICADOR               AS NOME_CLASSIFICADOR -- PARA NOMEAR


FROM TGFFIN FIN
         INNER JOIN TGFPAR PAR ON PAR.CODPARC = FIN.CODPARC
         INNER JOIN TGFNAT NAT ON NAT.CODNAT = FIN.CODNAT
         INNER JOIN TGFNAT PAI ON PAI.CODNAT = NAT.CODNATPAI
         INNER JOIN TGFNAT AVO ON AVO.CODNAT = PAI.CODNATPAI
         LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = FIN.CODCENCUS
         LEFT JOIN TSICUS CUSPAI ON CUSPAI.CODCENCUS = CUS.CODCENCUSPAI
         LEFT JOIN TSICUS CUSAVO ON CUSAVO.CODCENCUS = CUSPAI.CODCENCUSPAI
         INNER JOIN TGFITE ITE ON ITE.NUNOTA = FIN.NUNOTA
         INNER JOIN TGFTOP TTP ON TTP.CODTIPOPER = FIN.CODTIPOPER AND TTP.DHALTER = FIN.DHTIPOPER
         INNER JOIN AD_SQADRE CLAS ON CLAS.CODNAT = NAT.CODNAT

WHERE FIN.ORIGEM IN ('F', 'P','E')
  AND PROVISAO <> 'S'
  AND RECDESP IN (1,-1)
  AND FIN.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN

GROUP BY FIN.NUFIN
       , FIN.NUMNOTA
       , FIN.CODPARC
       , PAR.RAZAOSOCIAL
       , FIN.DTNEG
       , FIN.CODEMP
       , FIN.CODTIPOPER
       , TTP.DESCROPER
       , FIN.CODCENCUS
       , CUS.DESCRCENCUS
       , CUSPAI.CODCENCUS
       , CUSPAI.DESCRCENCUS
       , CUSAVO.CODCENCUS
       , CUSAVO.DESCRCENCUS
       , FIN.CODNAT
       , NAT.DESCRNAT
       , PAI.CODNAT
       , PAI.DESCRNAT
       , AVO.CODNAT
       , AVO.DESCRNAT
       , CLAS.ORDEM
       , CLAS.CLASSIFICADOR
       , FIN.RECDESP

HAVING SUM(FIN.VLRDESDOB) > 0